### ISSUE TITLE
Consistent Name

### ISSUE THREAD

**Issue by kacollins** [techlahoma/thunderplains-2020#5]
The site currently uses three different versions of the conference name:
- Thunderplains
- ThunderPlains
- Thunder Plains

Choose one version (`ThunderPlains` is the most commonly used) and update the others.

This would probably be a good issue for a newer dev to do for Hacktoberfest. :)

**Comment by shonamckenzie** [comment]
Hi @kacollins i can take a look at this if you like 🙂

**Comment by kacollins** [comment]
Please do, @shonamckenzie!

**Comment by shonamckenzie** [comment]
PR #9 ready for review

**Comment by kacollins** [comment]
Closed in #9
